package matroska

import "github.com/thesyncim/goav/container/ebml"

const (
	idEBML               ebml.ID = 0x1a45dfa3
	idEBMLVersion        ebml.ID = 0x4286
	idEBMLReadVersion    ebml.ID = 0x42f7
	idEBMLMaxIDLength    ebml.ID = 0x42f2
	idEBMLMaxSizeLength  ebml.ID = 0x42f3
	idDocType            ebml.ID = 0x4282
	idDocTypeVersion     ebml.ID = 0x4287
	idDocTypeReadVersion ebml.ID = 0x4285
	idCRC32              ebml.ID = 0xbf
	idVoid               ebml.ID = 0xec

	idSegment         ebml.ID = 0x18538067
	idSeekHead        ebml.ID = 0x114d9b74
	idSeek            ebml.ID = 0x4dbb
	idSeekID          ebml.ID = 0x53ab
	idSeekPosition    ebml.ID = 0x53ac
	idInfo            ebml.ID = 0x1549a966
	idSegmentUUID     ebml.ID = 0x73a4
	idSegmentFilename ebml.ID = 0x7384
	idPrevUUID        ebml.ID = 0x3cb923
	idPrevFilename    ebml.ID = 0x3c83ab
	idNextUUID        ebml.ID = 0x3eb923
	idNextFilename    ebml.ID = 0x3e83bb
	idTimestampScale  ebml.ID = 0x2ad7b1
	idDuration        ebml.ID = 0x4489
	idDateUTC         ebml.ID = 0x4461
	idTitle           ebml.ID = 0x7ba9
	idMuxingApp       ebml.ID = 0x4d80
	idWritingApp      ebml.ID = 0x5741

	idTracks               ebml.ID = 0x1654ae6b
	idTrackEntry           ebml.ID = 0xae
	idTrackNumber          ebml.ID = 0xd7
	idTrackUID             ebml.ID = 0x73c5
	idTrackType            ebml.ID = 0x83
	idFlagEnabled          ebml.ID = 0xb9
	idFlagDefault          ebml.ID = 0x88
	idFlagForced           ebml.ID = 0x55aa
	idFlagHearingImpaired  ebml.ID = 0x55ab
	idFlagVisualImpaired   ebml.ID = 0x55ac
	idFlagTextDescriptions ebml.ID = 0x55ad
	idFlagOriginal         ebml.ID = 0x55ae
	idFlagCommentary       ebml.ID = 0x55af
	idFlagLacing           ebml.ID = 0x9c
	idName                 ebml.ID = 0x536e
	idLanguage             ebml.ID = 0x22b59c
	idLanguageBCP          ebml.ID = 0x22b59d
	idCodecID              ebml.ID = 0x86
	idCodecName            ebml.ID = 0x258688
	idCodecPrivate         ebml.ID = 0x63a2
	idCodecDecodeAll       ebml.ID = 0xaa
	idCodecDelay           ebml.ID = 0x56aa
	idSeekPreRoll          ebml.ID = 0x56bb
	idMinCache             ebml.ID = 0x6de7
	idMaxCache             ebml.ID = 0x6df8
	idTrackOverlay         ebml.ID = 0x6fab
	idTrackTranslate       ebml.ID = 0x6624
	idTrackTranslateTrack  ebml.ID = 0x66a5
	idTrackTranslateCodec  ebml.ID = 0x66bf
	idTrackTranslateEdit   ebml.ID = 0x66fc
	idVideo                ebml.ID = 0xe0
	idFlagInterlaced       ebml.ID = 0x9a
	idFieldOrder           ebml.ID = 0x9d
	idStereoMode           ebml.ID = 0x53b8
	idAlphaMode            ebml.ID = 0x53c0
	idPixelWidth           ebml.ID = 0xb0
	idPixelHeight          ebml.ID = 0xba
	idPixelCropBottom      ebml.ID = 0x54aa
	idPixelCropTop         ebml.ID = 0x54bb
	idPixelCropLeft        ebml.ID = 0x54cc
	idPixelCropRight       ebml.ID = 0x54dd
	idDisplayWidth         ebml.ID = 0x54b0
	idDisplayHeight        ebml.ID = 0x54ba
	idDisplayUnit          ebml.ID = 0x54b2
	idAspectRatioType      ebml.ID = 0x54b3
	idColour               ebml.ID = 0x55b0
	idMatrixCoefficients   ebml.ID = 0x55b1
	idBitsPerChannel       ebml.ID = 0x55b2
	idChromaSubsampleHorz  ebml.ID = 0x55b3
	idChromaSubsampleVert  ebml.ID = 0x55b4
	idCbSubsampleHorz      ebml.ID = 0x55b5
	idCbSubsampleVert      ebml.ID = 0x55b6
	idChromaSitingHorz     ebml.ID = 0x55b7
	idChromaSitingVert     ebml.ID = 0x55b8
	idColourRange          ebml.ID = 0x55b9
	idTransferChar         ebml.ID = 0x55ba
	idPrimaries            ebml.ID = 0x55bb
	idMaxCLL               ebml.ID = 0x55bc
	idMaxFALL              ebml.ID = 0x55bd
	idMasteringMetadata    ebml.ID = 0x55d0
	idPrimaryRX            ebml.ID = 0x55d1
	idPrimaryRY            ebml.ID = 0x55d2
	idPrimaryGX            ebml.ID = 0x55d3
	idPrimaryGY            ebml.ID = 0x55d4
	idPrimaryBX            ebml.ID = 0x55d5
	idPrimaryBY            ebml.ID = 0x55d6
	idWhitePointX          ebml.ID = 0x55d7
	idWhitePointY          ebml.ID = 0x55d8
	idLuminanceMax         ebml.ID = 0x55d9
	idLuminanceMin         ebml.ID = 0x55da
	idProjection           ebml.ID = 0x7670
	idProjectionType       ebml.ID = 0x7671
	idProjectionPrivate    ebml.ID = 0x7672
	idProjectionPoseYaw    ebml.ID = 0x7673
	idProjectionPosePitch  ebml.ID = 0x7674
	idProjectionPoseRoll   ebml.ID = 0x7675
	idAudio                ebml.ID = 0xe1
	idSamplingFreq         ebml.ID = 0xb5
	idOutputFreq           ebml.ID = 0x78b5
	idChannels             ebml.ID = 0x9f
	idBitDepth             ebml.ID = 0x6264
	idDefaultDur           ebml.ID = 0x23e383
	idDefaultDecodedDur    ebml.ID = 0x234e7a
	idMaxBlockAdditionID   ebml.ID = 0x55ee
	idBlockAdditionMapping ebml.ID = 0x41e4
	idBlockAddIDValue      ebml.ID = 0x41f0
	idBlockAddIDName       ebml.ID = 0x41a4
	idBlockAddIDType       ebml.ID = 0x41e7
	idBlockAddIDExtraData  ebml.ID = 0x41ed

	idCluster           ebml.ID = 0x1f43b675
	idTimestamp         ebml.ID = 0xe7
	idSimpleBlock       ebml.ID = 0xa3
	idBlockGroup        ebml.ID = 0xa0
	idBlock             ebml.ID = 0xa1
	idBlockAdditions    ebml.ID = 0x75a1
	idBlockMore         ebml.ID = 0xa6
	idBlockAdditional   ebml.ID = 0xa5
	idBlockAddID        ebml.ID = 0xee
	idBlockDuration     ebml.ID = 0x9b
	idReferencePriority ebml.ID = 0xfa
	idReferenceBlk      ebml.ID = 0xfb
	idCodecState        ebml.ID = 0xa4
	idDiscardPad        ebml.ID = 0x75a2

	idCues               ebml.ID = 0x1c53bb6b
	idCuePoint           ebml.ID = 0xbb
	idCueTime            ebml.ID = 0xb3
	idCueTrackPositions  ebml.ID = 0xb7
	idCueTrack           ebml.ID = 0xf7
	idCueClusterPosition ebml.ID = 0xf1
	idCueRelativePos     ebml.ID = 0xf0
	idCueDuration        ebml.ID = 0xb2
	idCueBlockNumber     ebml.ID = 0x5378
	idCueCodecState      ebml.ID = 0xea
	idCueReference       ebml.ID = 0xdb
	idCueRefTime         ebml.ID = 0x96
	idCueRefCluster      ebml.ID = 0x97
	idCueRefNumber       ebml.ID = 0x535f
	idCueRefCodecState   ebml.ID = 0xeb

	idAttachments     ebml.ID = 0x1941a469
	idAttachedFile    ebml.ID = 0x61a7
	idFileDescription ebml.ID = 0x467e
	idFileName        ebml.ID = 0x466e
	idFileMediaType   ebml.ID = 0x4660
	idFileData        ebml.ID = 0x465c
	idFileUID         ebml.ID = 0x46ae

	idChapters           ebml.ID = 0x1043a770
	idEditionEntry       ebml.ID = 0x45b9
	idEditionUID         ebml.ID = 0x45bc
	idEditionFlagHidden  ebml.ID = 0x45bd
	idEditionFlagDefault ebml.ID = 0x45db
	idEditionFlagOrdered ebml.ID = 0x45dd
	idChapterAtom        ebml.ID = 0xb6
	idChapterUID         ebml.ID = 0x73c4
	idChapterStringUID   ebml.ID = 0x5654
	idChapterTimeStart   ebml.ID = 0x91
	idChapterTimeEnd     ebml.ID = 0x92
	idChapterFlagHidden  ebml.ID = 0x98
	idChapterFlagEnabled ebml.ID = 0x4598
	idChapterTrack       ebml.ID = 0x8f
	idChapterTrackUID    ebml.ID = 0x89
	idChapterDisplay     ebml.ID = 0x80
	idChapString         ebml.ID = 0x85
	idChapLanguage       ebml.ID = 0x437c
	idChapLanguageBCP47  ebml.ID = 0x437d
	idChapCountry        ebml.ID = 0x437e

	idTags             ebml.ID = 0x1254c367
	idTag              ebml.ID = 0x7373
	idTargets          ebml.ID = 0x63c0
	idTargetTypeValue  ebml.ID = 0x68ca
	idTargetType       ebml.ID = 0x63ca
	idTagTrackUID      ebml.ID = 0x63c5
	idTagEditionUID    ebml.ID = 0x63c9
	idTagChapterUID    ebml.ID = 0x63c4
	idTagAttachmentUID ebml.ID = 0x63c6
	idSimpleTag        ebml.ID = 0x67c8
	idTagName          ebml.ID = 0x45a3
	idTagLanguage      ebml.ID = 0x447a
	idTagLanguageBCP47 ebml.ID = 0x447b
	idTagDefault       ebml.ID = 0x4484
	idTagString        ebml.ID = 0x4487
	idTagBinary        ebml.ID = 0x4485
)

const (
	matroskaTrackVideo = 1
	matroskaTrackAudio = 2

	simpleBlockKeyframe    = 0x80
	simpleBlockInvisible   = 0x08
	simpleBlockLacingXiph  = 0x02
	simpleBlockLacingEBML  = 0x04
	simpleBlockLacingFixed = 0x06
	simpleBlockLacingMask  = 0x06
	simpleBlockDiscardable = 0x01
)
