// Package errcode names goav's structured error vocabulary. Family is the
// stable application branch key; Code is a detailed diagnostic leaf that may
// grow within a family before v1. Match errors with
// errors.As(err, *goav.BuildError), switch on Family first, and use Code when
// a caller needs a specific diagnostic leaf. Rendered text may improve over
// time. See docs/ERRORS.md for the contract and matching recipes.
package errcode

// Code identifies a detailed BuildError refusal leaf. Families are the stable
// application-level matching surface; codes are the detailed diagnostic surface.
//
// Code is an open string, not a closed enum: external components emit their
// own vendor-prefixed codes through the same BuildError shape, and they flow
// through matching and rendering unchanged. The catalog below is goav's own
// vocabulary, not the universe of valid errcode.
type Code string

// Family identifies the stable high-level BuildError class. Code is the
// detailed diagnostic leaf during the typed-error migration; Family is the
// field callers should switch on before inspecting a specific catalog code.
type Family string

const (
	// FamilyInput groups input, source, probing, and source-shape refusals.
	FamilyInput Family = "input"
	// FamilyStream groups stream selection and stream-chain ordering refusals.
	FamilyStream Family = "stream"
	// FamilyFlow groups reusable Flow fragment refusals.
	FamilyFlow Family = "flow"
	// FamilyTransform groups explicit transform and transform adapter refusals.
	FamilyTransform Family = "transform"
	// FamilyShape groups shape requirement and automatic-conversion refusals.
	FamilyShape Family = "shape"
	// FamilyCodec groups codec adapter availability and capability refusals.
	FamilyCodec Family = "codec"
	// FamilyEncode groups encoder-stage and encoder-setting refusals.
	FamilyEncode Family = "encode"
	// FamilyDestination groups output, destination, muxer, and sink refusals.
	FamilyDestination Family = "destination"
	// FamilyBranch groups build-time branch grammar and composition refusals.
	FamilyBranch Family = "branch"
	// FamilyBuffer groups branch and graph buffer safety refusals.
	FamilyBuffer Family = "buffer"
	// FamilyTap groups tap declaration and tap-domain refusals.
	FamilyTap Family = "tap"
	// FamilyJoin groups Mix, Composite, Select, and custom Join refusals.
	FamilyJoin Family = "join"
	// FamilyRuntimeBranch groups Mutable.Attach and rebranch refusals.
	FamilyRuntimeBranch Family = "runtime_branch"
	// FamilyStreamRule groups OnStream rule grammar refusals.
	FamilyStreamRule Family = "stream_rule"
	// FamilyCompiler groups compiler and internal graph-plan refusals.
	FamilyCompiler Family = "compiler"
	// FamilyExternal groups vendor-prefixed or otherwise uncataloged codes.
	FamilyExternal Family = "external"
)

const familyDiagnostic Family = "diagnostic"

const (
	branchComposePlanEmpty   = Code("branch_compose_plan_empty")
	compilerPassInvalid      = Code("compiler_pass_invalid")
	compilerPassFailed       = Code("compiler_pass_failed")
	recipeAttachmentMismatch = Code("recipe_attachment_mismatch")
	graphPlanInvalid         = Code("graph_plan_invalid")
	bufferBudgetMissing      = Code("buffer_budget_missing")
)

// FamilyForCode returns the stable family for a goav error code. It also
// recognizes goav's non-failing plan diagnostic strings for report grouping.
// Unknown vendor-prefixed codes fall back to FamilyExternal. Custom join codes
// generated by goav.Join use the same suffix families as built-in joins.
func FamilyForCode(code Code) Family {
	switch code {
	case InputInvalid, InputMissing, InputDuplicate, InputUnknown,
		InputCountUnsupported, InputFormatUnknown, InputDemuxerMissing,
		MultiInputUnsupported, UnsupportedInput, SourceCallbackMissing,
		SourceShapeInvalid, SourceShapeUnsupported, SourceShapeMismatch,
		ExplicitGraphSourceMissing:
		return FamilyInput
	case StreamMissing, StreamAmbiguous, StreamDuplicate, StreamNameMissing,
		StreamSelectorInvalid, StreamCodecMissing, StreamOperationMissing,
		StreamStepAfterEncode, StageMissing:
		return FamilyStream
	case Code("flow_invalid"), Code("flow_media_mismatch"), Code("flow_decode_duplicate"),
		Code("flow_decode_order_invalid"), Code("flow_decode_domain_mismatch"), Code("flow_copy_domain_mismatch"):
		return FamilyFlow
	case TransformInvalid, TransformMediaMismatch, TransformAdapterMissing,
		TransformAdapterIncompatible, TranscodeResizeInvalid,
		OperationShapeMismatch:
		return FamilyTransform
	case ShapeRequirementUnmet, ShapeConversionRefused, ShapeAdapterMissing,
		ShapeAdapterAmbiguous:
		return FamilyShape
	case DecodeAdapterMissing, DecodeAdapterUnavailable, DecodeAdapterIncompatible,
		EncodeAdapterMissing, EncodeAdapterUnavailable, EncodeAdapterIncompatible,
		CodecChangePolicyUnsupported:
		return FamilyCodec
	case EncodeMissing, EncodeDuplicate, EncodeParameterInvalid,
		EncodeAutoUnresolved, EncodeStreamMismatch,
		EncodeDestinationMissing, EncodeBranchSourceInvalid:
		return FamilyEncode
	case Code("output_invalid"), Code("output_missing"), Code("output_duplicate"),
		Code("output_scope_mixed"), Code("output_kind_mixed"), Code("output_writer_missing"),
		Code("output_format_missing"), Code("output_format_unknown"), Code("output_muxer_missing"),
		Code("output_destination_missing"), Code("destination_invalid"), Code("destination_missing"),
		Code("destination_duplicate"), Code("destination_format_unknown"), Code("destination_muxer_missing"),
		Code("destination_mux_incompatible"), Code("destination_shape_mismatch"):
		return FamilyDestination
	case Code("branch_invalid"), Code("branch_missing"), Code("branch_duplicate"),
		Code("branch_source_invalid"), Code("branch_tap_missing"), Code("branch_decode_duplicate"),
		Code("branch_decode_order_invalid"), Code("branch_decode_domain_mismatch"),
		Code("branch_decode_copy_invalid"), Code("branch_transform_media_mismatch"),
		Code("branch_destination_invalid"), Code("branch_destination_unmatched"),
		Code("branch_operation_chain_unsupported"), branchComposePlanEmpty,
		Code("copy_branch_source_invalid"), Code("copy_unsupported"),
		Code("packet_branch_encode_unsupported"), Code("packet_branch_transform_unsupported"),
		Code("decode_config_conflict"), Code("decode_policy_conflict"):
		return FamilyBranch
	case Code("branch_buffer_invalid"), Code("branch_buffer_unsupported"),
		Code("buffer_payload_unsafe"), Code("buffer_payload_too_large"), bufferBudgetMissing:
		return FamilyBuffer
	case TapInvalid, TapDomainMismatch:
		return FamilyTap
	case JoinNameInvalid, JoinStageInvalid:
		return FamilyJoin
	case Code("runtime_branch_invalid"), Code("runtime_branch_anchor_missing"),
		Code("runtime_branch_tap_missing"), Code("runtime_branch_tap_duplicate"),
		Code("runtime_branch_node_duplicate"), Code("runtime_branch_encode_missing"),
		Code("runtime_branch_encode_domain_mismatch"), Code("runtime_branch_decode_domain_mismatch"),
		Code("runtime_branch_decode_codec_missing"), Code("runtime_branch_copy_domain_mismatch"),
		Code("runtime_branch_mux_codec_missing"), Code("runtime_branch_transform_error"),
		Code("runtime_branch_graph_error"):
		return FamilyRuntimeBranch
	case StreamRuleInvalid:
		return FamilyStreamRule
	case JobInvalid, RuntimeMissing, compilerPassInvalid, compilerPassFailed,
		RecipeGraphUnsupported, recipeAttachmentMismatch, graphPlanInvalid:
		return FamilyCompiler
	case Code("shape_conversion_inserted"), Code("shape_preference_applied"), Code("shape_preference_ignored"),
		Code("decode_codec_deferred"), Code("explain_preflight_error"), Code("packet_copy"),
		Code("frame_source"), Code("event_source"), Code("decode_required"), Code("encode_required"),
		Code("stream_rule"):
		return familyDiagnostic
	default:
		if isCustomJoinCode(code) {
			return FamilyJoin
		}
		return FamilyExternal
	}
}

func isCustomJoinCode(code Code) bool {
	name := string(code)
	return hasSuffix(name, "_inputs") ||
		hasSuffix(name, "_arm") ||
		hasSuffix(name, "_destination") ||
		hasSuffix(name, "_tap_arm")
}

func hasSuffix(name string, suffix string) bool {
	return len(name) >= len(suffix) && name[len(name)-len(suffix):] == suffix
}

// Input and source errcode.
const (
	// InputInvalid fires when an input spec is empty or carries a
	// construction error (a nil reader, a failed provider option).
	InputInvalid Code = "input_invalid"
	// InputMissing fires when a job reaches Build with no input configured.
	InputMissing Code = "input_missing"
	// InputDuplicate fires when two realtime inputs declare the same name.
	InputDuplicate Code = "input_duplicate"
	// InputUnknown fires when goav.InputName(...) names no job input.
	InputUnknown Code = "input_unknown"
	// InputCountUnsupported fires when a recipe form that takes one input
	// (transcode, branch fanout) is given several.
	InputCountUnsupported Code = "input_count_unsupported"
	// InputFormatUnknown fires when probing cannot detect the input format.
	InputFormatUnknown Code = "input_format_unknown"
	// InputDemuxerMissing fires when the input format was detected but the
	// runtime has no demuxer registered for it.
	InputDemuxerMissing Code = "input_demuxer_missing"
	// MultiInputUnsupported fires when several recipe inputs mix kinds the
	// multi-input compiler does not support yet.
	MultiInputUnsupported Code = "multi_input_unsupported"
	// UnsupportedInput fires when a live provider input reaches the
	// transcode recipe compiler, which does not accept it yet.
	UnsupportedInput Code = "unsupported_input"
	// SourceCallbackMissing fires when a custom source declares no push
	// callback.
	SourceCallbackMissing Code = "source_callback_missing"
	// SourceShapeInvalid fires when a custom source shape has no media kind.
	SourceShapeInvalid Code = "source_shape_invalid"
	// SourceShapeUnsupported fires when a custom source declares a media
	// domain other than packet, frame, or event.
	SourceShapeUnsupported Code = "source_shape_unsupported"
	// SourceShapeMismatch fires when a chain operation contradicts the
	// declared custom-source shape (decoding already-decoded frames, packet
	// copy from a frame source).
	SourceShapeMismatch Code = "source_shape_mismatch"
	// ExplicitGraphSourceMissing fires when an expert graph plan has no
	// source node.
	ExplicitGraphSourceMissing Code = "explicit_graph_source_missing"
)

// Stream selection errcode.
const (
	// StreamMissing fires when no stream matches the chain's selector.
	StreamMissing Code = "stream_missing"
	// StreamAmbiguous fires when several streams match the chain's
	// selector and goav cannot pick one.
	StreamAmbiguous Code = "stream_ambiguous"
	// StreamDuplicate fires when two stream chains or branches resolve to
	// the same name or selection.
	StreamDuplicate Code = "stream_duplicate"
	// StreamNameMissing fires when a planned branch has no stable name.
	StreamNameMissing Code = "stream_name_missing"
	// StreamSelectorInvalid fires when a selector is malformed (negative
	// stream index).
	StreamSelectorInvalid Code = "stream_selector_invalid"
	// StreamCodecMissing fires when the selected packet stream carries no
	// codec id, so it cannot be decoded.
	StreamCodecMissing Code = "stream_codec_missing"
	// StreamOperationMissing fires when a chain selects a stream but
	// requests no decode, processing stage, or encoder.
	StreamOperationMissing Code = "stream_operation_missing"
	// StreamStepAfterEncode fires when a processing step is declared after
	// the terminal encoder.
	StreamStepAfterEncode Code = "stream_step_after_encode"
	// StageMissing fires when a custom stream stage is nil.
	StageMissing Code = "stage_missing"
)

// Transform and shape errcode.
const (
	// TransformInvalid fires when a transform is empty, conflicting, or
	// malformed (one transform declaring both resize and resample).
	TransformInvalid Code = "transform_invalid"
	// TransformMediaMismatch fires when a transform is applied to the
	// wrong media kind (resize on audio, resample on video).
	TransformMediaMismatch Code = "transform_media_mismatch"
	// TransformAdapterMissing fires when no filter adapter is registered
	// for the requested transform.
	TransformAdapterMissing Code = "transform_adapter_missing"
	// TransformAdapterIncompatible fires when the registered filter
	// adapter does not support the requested configuration.
	TransformAdapterIncompatible Code = "transform_adapter_incompatible"
	// TranscodeResizeInvalid fires when a transcode resize has invalid
	// dimensions.
	TranscodeResizeInvalid Code = "transcode_resize_invalid"
	// OperationShapeMismatch fires when an operation cannot consume the
	// media shape the chain produces at that point.
	OperationShapeMismatch Code = "operation_shape_mismatch"
	// ShapeRequirementUnmet fires when a .Require(...) assertion is not
	// satisfied and no active .Auto(...) policy covers the conversion.
	ShapeRequirementUnmet Code = "shape_requirement_unmet"
	// ShapeConversionRefused fires when a needed conversion exists but the
	// chain's .Auto(...) policy does not allow it.
	ShapeConversionRefused Code = "shape_conversion_refused"
	// ShapeAdapterMissing fires when no registered filter can perform a
	// needed conversion.
	ShapeAdapterMissing Code = "shape_adapter_missing"
	// ShapeAdapterAmbiguous fires when several registered filters could
	// perform a needed conversion and no .Prefer(...) resolves the choice.
	ShapeAdapterAmbiguous Code = "shape_adapter_ambiguous"
)

// Codec adapter codes (decode/encode availability and capability).
const (
	// DecodeAdapterMissing fires when no decoder adapter is registered for
	// the stream's codec.
	DecodeAdapterMissing Code = "decode_adapter_missing"
	// DecodeAdapterUnavailable fires when the decoder adapter is
	// descriptor-only in this build (missing build tag).
	DecodeAdapterUnavailable Code = "decode_adapter_unavailable"
	// DecodeAdapterIncompatible fires when the decoder adapter does not
	// support the requested media or frame format.
	DecodeAdapterIncompatible Code = "decode_adapter_incompatible"
	// EncodeAdapterMissing fires when no encoder adapter is registered for
	// the requested codec.
	EncodeAdapterMissing Code = "encode_adapter_missing"
	// EncodeAdapterUnavailable fires when the encoder adapter is
	// descriptor-only in this build (missing build tag).
	EncodeAdapterUnavailable Code = "encode_adapter_unavailable"
	// EncodeAdapterIncompatible fires when the encoder adapter does not
	// support the requested media or frame format.
	EncodeAdapterIncompatible Code = "encode_adapter_incompatible"
	// CodecChangePolicyUnsupported fires when a custom codec-change policy
	// is requested; only the default live receive behavior is supported today.
	CodecChangePolicyUnsupported Code = "codec_change_policy_unsupported"
)

// Encode errcode.
const (
	// EncodeMissing fires when decoded frames are routed to a muxed
	// destination without an encoder.
	EncodeMissing Code = "encode_missing"
	// EncodeDuplicate fires when a chain declares a second terminal
	// encoder.
	EncodeDuplicate Code = "encode_duplicate"
	// EncodeParameterInvalid fires when an encode setting is out of range
	// (negative bitrate, non-positive FPS).
	EncodeParameterInvalid Code = "encode_parameter_invalid"
	// EncodeAutoUnresolved fires when automatic codec selection is
	// requested where it is not implemented.
	EncodeAutoUnresolved Code = "encode_auto_unresolved"
	// EncodeStreamMismatch fires when the encoder's stream selector does
	// not match the stream the chain decoded.
	EncodeStreamMismatch Code = "encode_stream_mismatch"
	// EncodeDestinationMissing fires when an encode stage is built with no
	// target codec.
	EncodeDestinationMissing Code = "encode_destination_missing"
	// EncodeBranchSourceInvalid fires when a planned branch anchors after
	// a terminal stream encoder.
	EncodeBranchSourceInvalid Code = "encode_branch_source_invalid"
)

// Tap errcode.
const (
	// TapInvalid fires when a tap name is empty.
	TapInvalid Code = "tap_invalid"
	// TapDomainMismatch fires when a typed tap's domain (frame/packet)
	// does not match the chain point it is declared on.
	TapDomainMismatch Code = "tap_domain_mismatch"
)

// Join codes. Built-in and custom join profile refusals derive per-kind codes
// as <kind>_<family> through goav's joinErrorCode helper; custom joins use the
// same families under their own snake-safe names. The explicit catalog here is
// limited to constructor/name validation that does not derive from a profile.
const (
	// JoinNameInvalid fires when a custom join (goav.Join) declares an
	// unusable name: empty, not snake-safe ([a-z][a-z0-9_]*), reserved by a
	// built-in kind (mix, composite, select), or colliding with another join
	// node in the same join tree.
	JoinNameInvalid Code = "join_name_invalid"
	// JoinStageInvalid fires when a custom join's convergence stage is nil
	// or reports a Name() different from the join's name.
	JoinStageInvalid Code = "join_stage_invalid"
)

// Stream rule codes (OnStream grammar).
const (
	// StreamRuleInvalid fires when an OnStream rule is malformed (no
	// matcher, no branch, or an unusable discovered stream).
	StreamRuleInvalid Code = "stream_rule_invalid"
)

// Job and compiler errcode.
const (
	// JobInvalid fires when a nil, zero, or otherwise unconstructed job or
	// join reaches the recipe compiler.
	JobInvalid Code = "job_invalid"
	// RuntimeMissing fires when a job reaches Build with no runtime
	// configured.
	RuntimeMissing Code = "runtime_missing"
	// RecipeGraphUnsupported fires when the recipe intent matches no
	// supported graph plan.
	RecipeGraphUnsupported Code = "recipe_graph_unsupported"
)
