package goav

import "github.com/thesyncim/goav/errcode"

const (
	branchComposePlanEmptyCode   errcode.Code = "branch_compose_plan_empty"
	compilerPassInvalidCode      errcode.Code = "compiler_pass_invalid"
	compilerPassFailedCode       errcode.Code = "compiler_pass_failed"
	recipeAttachmentMismatchCode errcode.Code = "recipe_attachment_mismatch"
	graphPlanInvalidCode         errcode.Code = "graph_plan_invalid"
	bufferBudgetMissingCode      errcode.Code = "buffer_budget_missing"

	flowInvalidCode              errcode.Code = "flow_invalid"
	flowMediaMismatchCode        errcode.Code = "flow_media_mismatch"
	flowDecodeDuplicateCode      errcode.Code = "flow_decode_duplicate"
	flowDecodeOrderInvalidCode   errcode.Code = "flow_decode_order_invalid"
	flowDecodeDomainMismatchCode errcode.Code = "flow_decode_domain_mismatch"
	flowCopyDomainMismatchCode   errcode.Code = "flow_copy_domain_mismatch"

	branchInvalidCode                    errcode.Code = "branch_invalid"
	branchMissingCode                    errcode.Code = "branch_missing"
	branchDuplicateCode                  errcode.Code = "branch_duplicate"
	branchSourceInvalidCode              errcode.Code = "branch_source_invalid"
	branchTapMissingCode                 errcode.Code = "branch_tap_missing"
	branchDecodeDuplicateCode            errcode.Code = "branch_decode_duplicate"
	branchDecodeOrderInvalidCode         errcode.Code = "branch_decode_order_invalid"
	branchDecodeDomainMismatchCode       errcode.Code = "branch_decode_domain_mismatch"
	branchDecodeCopyInvalidCode          errcode.Code = "branch_decode_copy_invalid"
	branchTransformMediaMismatchCode     errcode.Code = "branch_transform_media_mismatch"
	branchDestinationInvalidCode         errcode.Code = "branch_destination_invalid"
	branchDestinationUnmatchedCode       errcode.Code = "branch_destination_unmatched"
	branchOperationChainUnsupportedCode  errcode.Code = "branch_operation_chain_unsupported"
	branchBufferInvalidCode              errcode.Code = "branch_buffer_invalid"
	branchBufferUnsupportedCode          errcode.Code = "branch_buffer_unsupported"
	bufferPayloadUnsafeCode              errcode.Code = "buffer_payload_unsafe"
	bufferPayloadTooLargeCode            errcode.Code = "buffer_payload_too_large"
	copyBranchSourceInvalidCode          errcode.Code = "copy_branch_source_invalid"
	copyUnsupportedCode                  errcode.Code = "copy_unsupported"
	packetBranchEncodeUnsupportedCode    errcode.Code = "packet_branch_encode_unsupported"
	packetBranchTransformUnsupportedCode errcode.Code = "packet_branch_transform_unsupported"
	decodeConfigConflictCode             errcode.Code = "decode_config_conflict"
	decodePolicyConflictCode             errcode.Code = "decode_policy_conflict"

	outputInvalidCode              errcode.Code = "output_invalid"
	outputMissingCode              errcode.Code = "output_missing"
	outputDuplicateCode            errcode.Code = "output_duplicate"
	outputScopeMixedCode           errcode.Code = "output_scope_mixed"
	outputKindMixedCode            errcode.Code = "output_kind_mixed"
	outputWriterMissingCode        errcode.Code = "output_writer_missing"
	outputFormatMissingCode        errcode.Code = "output_format_missing"
	outputFormatUnknownCode        errcode.Code = "output_format_unknown"
	outputMuxerMissingCode         errcode.Code = "output_muxer_missing"
	outputDestinationMissingCode   errcode.Code = "output_destination_missing"
	destinationInvalidCode         errcode.Code = "destination_invalid"
	destinationMissingCode         errcode.Code = "destination_missing"
	destinationDuplicateCode       errcode.Code = "destination_duplicate"
	destinationFormatUnknownCode   errcode.Code = "destination_format_unknown"
	destinationMuxerMissingCode    errcode.Code = "destination_muxer_missing"
	destinationMuxIncompatibleCode errcode.Code = "destination_mux_incompatible"
	destinationShapeMismatchCode   errcode.Code = "destination_shape_mismatch"

	transformInvalidCode             errcode.Code = "transform_invalid"
	transformMediaMismatchCode       errcode.Code = "transform_media_mismatch"
	transformAdapterMissingCode      errcode.Code = "transform_adapter_missing"
	transformAdapterIncompatibleCode errcode.Code = "transform_adapter_incompatible"
	transcodeResizeInvalidCode       errcode.Code = "transcode_resize_invalid"
	operationShapeMismatchCode       errcode.Code = "operation_shape_mismatch"
	shapeRequirementUnmetCode        errcode.Code = "shape_requirement_unmet"
	shapeConversionRefusedCode       errcode.Code = "shape_conversion_refused"
	shapeAdapterMissingCode          errcode.Code = "shape_adapter_missing"
	shapeAdapterAmbiguousCode        errcode.Code = "shape_adapter_ambiguous"
	decodeAdapterMissingCode         errcode.Code = "decode_adapter_missing"
	decodeAdapterUnavailableCode     errcode.Code = "decode_adapter_unavailable"
	decodeAdapterIncompatibleCode    errcode.Code = "decode_adapter_incompatible"
	encodeAdapterMissingCode         errcode.Code = "encode_adapter_missing"
	encodeAdapterUnavailableCode     errcode.Code = "encode_adapter_unavailable"
	encodeAdapterIncompatibleCode    errcode.Code = "encode_adapter_incompatible"
	codecChangePolicyUnsupportedCode errcode.Code = "codec_change_policy_unsupported"
	encodeMissingCode                errcode.Code = "encode_missing"
	encodeDuplicateCode              errcode.Code = "encode_duplicate"
	encodeParameterInvalidCode       errcode.Code = "encode_parameter_invalid"
	encodeAutoUnresolvedCode         errcode.Code = "encode_auto_unresolved"
	encodeStreamMismatchCode         errcode.Code = "encode_stream_mismatch"
	encodeDestinationMissingCode     errcode.Code = "encode_destination_missing"
	encodeBranchSourceInvalidCode    errcode.Code = "encode_branch_source_invalid"

	runtimeBranchInvalidCode              errcode.Code = "runtime_branch_invalid"
	runtimeBranchAnchorMissingCode        errcode.Code = "runtime_branch_anchor_missing"
	runtimeBranchTapMissingCode           errcode.Code = "runtime_branch_tap_missing"
	runtimeBranchTapDuplicateCode         errcode.Code = "runtime_branch_tap_duplicate"
	runtimeBranchNodeDuplicateCode        errcode.Code = "runtime_branch_node_duplicate"
	runtimeBranchEncodeMissingCode        errcode.Code = "runtime_branch_encode_missing"
	runtimeBranchEncodeDomainMismatchCode errcode.Code = "runtime_branch_encode_domain_mismatch"
	runtimeBranchDecodeDomainMismatchCode errcode.Code = "runtime_branch_decode_domain_mismatch"
	runtimeBranchDecodeCodecMissingCode   errcode.Code = "runtime_branch_decode_codec_missing"
	runtimeBranchCopyDomainMismatchCode   errcode.Code = "runtime_branch_copy_domain_mismatch"
	runtimeBranchMuxCodecMissingCode      errcode.Code = "runtime_branch_mux_codec_missing"
	runtimeBranchTransformErrorCode       errcode.Code = "runtime_branch_transform_error"
	runtimeBranchGraphErrorCode           errcode.Code = "runtime_branch_graph_error"
)
